receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/digma:
    endpoint: ${OTLP_EXPORTER_DIGMA_COLLECTOR_API}
    tls:
      insecure: true
  otlp/elastic:
    endpoint: "elastic-apm-server:8200"     
    tls:
      insecure: true
    headers:
      Authorization: "Bearer XXXXXXXXXXXXXXX"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger,otlp/digma,otlp/elastic]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
