version: "3.6"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250"
      - "0.0.0.0:14268:14268"
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#      - "0.0.0.0:9411:9411"

#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"

  collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.48.0
    command: ["--config=/otel-local-config.yaml"]
    volumes:
      - ./collector-config.yaml:/otel-local-config.yaml
    ports:
      #- "0.0.0.0:8889:8889"   # Prometheus exporter metrics
      - "0.0.0.0:4317:4317" # OTLP receiver
    depends_on:
      - jaeger
    environment:
      - OTLP_EXPORTER_DIGMA_COLLECTOR_API=host.docker.internal:5060
    extra_hosts:
      - "host.docker.internal:host-gateway"

  apm-server:
    container_name: elastic-apm-server
    image: 'docker.elastic.co/apm/apm-server:7.13.0'
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    ports:
      - '8200:8200'
    command: |
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: >-
        curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  elasticsearch:
    container_name: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.0'
    ports:
      - '9200:9200'
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: 'docker.elastic.co/kibana/kibana:7.13.0'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    environment:
      - 'ELASTICSEARCH_URL=http://localhost:9200'
      - xpack.apm.enabled=false

volumes:
    elasticsearch-data: null

networks:
  default:
    name: digma-network
